Update Readme.md
Analytics-Verse/spark pull request #1
Opened 2021-06-17 16:56 UTC by shharrnam

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

2021-06-17 16:58 UTC, shharrnam reviewed
Commenting

2021-06-17 16:58 UTC, shharrnam commented on README.md
> +# Apache Spark 2
Commenting

2021-11-16 06:25 UTC, shharrnam commented
Commenting on MR

2021-11-16 06:25 UTC, shharrnam commented
> Commenting on MR

Reply to comment on MR

2021-11-16 06:26 UTC, shharrnam commented on README.md
> +# Apache Spark 2
Reply to comment on code

2021-11-16 06:26 UTC, shharrnam reviewed
Final Review Comment

2021-11-16 06:27 UTC, shharrnam commented on README.md
>  Spark is a unified analytics engine for large-scale data processing. It provides
Code comment

2021-11-16 06:27 UTC, shharrnam commented on README.md
>  high-level APIs in Scala, Java, Python, and R, and an optimized engine that
Code comment 2

2021-11-16 06:27 UTC, shharrnam commented on README.md
>  Spark is a unified analytics engine for large-scale data processing. It provides
Code comment 3

2021-11-16 08:09 UTC, shharrnam commented on README.md
> -# Apache Spark
why?

2021-11-16 08:10 UTC, shharrnam reviewed
why2 heading

2021-11-16 08:10 UTC, shharrnam commented on README.md
> -# Apache Spark
why2?

2021-11-16 08:11 UTC, shharrnam commented on README.md
> -# Apache Spark
why3?

2021-11-16 08:11 UTC, shharrnam commented on README.md
>  Spark is a unified analytics engine for large-scale data processing. It provides
reply to code comment3

2021-11-16 11:03 UTC, shharrnam reviewed
Top comment on review

2021-11-16 11:03 UTC, shharrnam commented on README.md
> +# Apache Spark 2
Comment 1 with review

2021-11-16 11:03 UTC, shharrnam commented on README.md
>  high-level APIs in Scala, Java, Python, and R, and an optimized engine that
Comment 2 with review

2021-11-16 11:04 UTC, shharrnam commented on README.md
> -# Apache Spark
Comment3 with review

2021-11-16 11:04 UTC, shharrnam commented on README.md
> +# Apache Spark 2
Comment 4 with review

2021-11-16 11:04 UTC, shharrnam commented on README.md
Comment 5 with review

2021-11-16 11:05 UTC, shharrnam commented on README.md
Comment6 without review

2021-11-16 11:06 UTC, shharrnam commented on README.md
>  high-level APIs in Scala, Java, Python, and R, and an optimized engine that
Reply to comment2

2021-11-18 19:00 UTC, shharrnam reviewed
Review Comment - Starting a review for Breejesh to comment

2021-11-18 19:02 UTC, shharrnam commented
Top level comment

2021-11-18 19:05 UTC, breejesh2212 commented on README.md
> -# Apache Spark
Added a comment

2021-11-19 08:03 UTC, shharrnam commented
Top level comment 2

2021-11-20 07:55 UTC, dharinp requested changes
Hi hello request change

2021-11-20 07:55 UTC, dharinp commented on README.md
> -# Apache Spark
Hi hello

2021-11-20 07:55 UTC, dharinp approved these changes
This is approve testing

2021-11-20 07:55 UTC, dharinp commented on README.md
> -# Apache Spark
Testing 2

2021-11-20 07:56 UTC, dharinp approved these changes

2021-11-20 08:28 UTC, shharrnam commented
Closing MR With comment

2021-11-20 08:28 UTC, closed without merging